### ISSUE TITLE
What are the differences between git repository and googlecode repository?

### ISSUE THREAD

**Issue by gryphon2411** [googlearchive/js-map-label#7]
It seems that there are differences between git repository (this) and [googlecode repository](http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerwithlabel/).

I'd noticed the difference by the _difference between the labeled marker object name_ in both repositories (googlecode repository - `MarkerWithLabel`, git repository - `MapLabel`).
Also, there is a difference in the object interaction with the map (googlecode repository - Constructing `MarkerWithLabel` object instead of `google.maps.Marker` object, git repository - bind constructed `google.maps.Marker` object to constructed `MapLabel` object).

I would really like to know **who is the newest and most supported** by the contributors, are they providing the same solution to the users marker requirements?

Thank you.

**Comment by broady** [comment]
google code is deprecated, so _nothing_ on that site is up to date. github is the latest version.
